// This file is generated by Firebase Studio.
'use server';
/**
 * @fileOverview A data extraction AI agent.
 *
 * - automateDataExtraction - A function that handles the data extraction process.
 * - AutomateDataExtractionInput - The input type for the automateDataExtraction function.
 * - AutomateDataExtractionOutput - The return type for the automateDataExtraction function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AutomateDataExtractionInputSchema = z.object({
  extractionInstructions: z
    .string()
    .describe("Instructions on how the agent should perform data extraction, including details for scheduled API calls, streaming data capture, and web scraping."),
});
export type AutomateDataExtractionInput = z.infer<typeof AutomateDataExtractionInputSchema>;

const AutomateDataExtractionOutputSchema = z.object({
  extractionDetails: z.object({
    method: z.string().describe('The method used for data extraction (e.g., API call, streaming, web scraping).'),
    schedule: z.string().optional().describe('The schedule for data extraction, if applicable (e.g., cron expression).'),
    source: z.string().describe('The source of the data (e.g., API endpoint, stream URL, website URL).'),
    transformationScript: z.string().optional().describe('A Python script to transform the data after extraction, if transformation is required.'),
  }).describe('Details about the automated data extraction process.'),
  status: z.string().describe('The status of the data extraction setup (e.g., pending, active, failed).'),
});
export type AutomateDataExtractionOutput = z.infer<typeof AutomateDataExtractionOutputSchema>;

export async function automateDataExtraction(input: AutomateDataExtractionInput): Promise<AutomateDataExtractionOutput> {
  return automateDataExtractionFlow(input);
}

const prompt = ai.definePrompt({
  name: 'automateDataExtractionPrompt',
  input: {schema: AutomateDataExtractionInputSchema},
  output: {schema: AutomateDataExtractionOutputSchema},
  prompt: `You are an expert data engineer specializing in automating data extraction from various sources.

You will receive instructions on how to perform data extraction, and you must determine the appropriate method, schedule (if applicable), and source of the data.

Based on the instructions, provide details about the automated data extraction process, including the method, schedule, source, and a Python script for data transformation if necessary.

Instructions: {{{extractionInstructions}}}

Ensure the output is a valid JSON object that adheres to the AutomateDataExtractionOutputSchema.

Consider the necessity for a transformation script based on the extraction method. If API is called which returns a data set, you may skip transformation.
`,
});

const automateDataExtractionFlow = ai.defineFlow(
  {
    name: 'automateDataExtractionFlow',
    inputSchema: AutomateDataExtractionInputSchema,
    outputSchema: AutomateDataExtractionOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
